### ISSUE TITLE
Where did Signals go?

### ISSUE THREAD

**Issue by gngriffiths** [UniDi/UniDi#55]
### Feature already in UniDi?

Extenject

### Feature description

Signals appear to be missing from UniDi:

https://github.com/Mathijs-Bakker/Extenject/blob/master/Documentation/Signals.md

**Comment by Mathijs-Bakker** [comment]
Originally you could find SignalBus in Zenject/Extenjects ``Optional Extras`` folder.
Everything which has no direct relation with dependency injection container behavior has been stripped out from the UniDi core repo.

All those parts that are 'add-ons', libraries, demos, etc. will be available in it's own repo.
The Signals repo you can find here: [UniDi/UniDi-Signals](https://github.com/UniDi/UniDi-Signals).

**Comment by gngriffiths** [comment]
Thanks for clarifying Mathijs-Bakker
